### ISSUE TITLE
MULTIseq.preProcess

### ISSUE THREAD

**Issue by lk9-lnx** [chris-mcginnis-ucsf/MULTI-seq#2]
I'm using MULTI-seq on hashing data. I'm getting the following error when I tried to use MULTIseq.preProcess function. Is there an issue?

Error in .Call2("solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  : 
  solving row 1: 'allow.nonnarrowing' is FALSE and the supplied end (28) is > refwidth

**Comment by lk9-lnx** [comment]
What does 'good.bars' refer to in the tutorial?

**Comment by chris-mcginnis-ucsf** [comment]
Apologies for the delayed response. 

This error is likely caused because your sequencing settings only took the first 26 bases of R1, and the default chemistry argument previously looked at the first 28 bases. I've adjusted the arguments to make this more flexible, and have also included a more specific description of 'good.bars' in the ReadMe. 

Chris

**Comment by RM-SCB** [comment]
I got into the same confusion, but then found this issue and realised 26 was the number to use. Might be worth either editing the tutorial with 26 instead of 28 or adding a line to flag it so that people not careful enough like me make sure to edit this! :)

**Comment by chris-mcginnis-ucsf** [comment]
The 10x V3 reagents have CB=16bp and UMI=12bp, whereas 10x V2 reagents have CB=16bp and UMI=10bp. Since V2 reagents are being phased out, I think it makes sense to keep the current default arguments. But I like the idea of adding some sort of flag!

**Comment by uni987** [comment]
What is a nice job! I have been tried to use three cellIDs label fragments to improve its stability, however, how can I adjust the arguments to make it. I am looking forward to your prompt reply!! Thanks

**Comment by uni987** [comment]
What is a nice job! I have been trying to use three cellIDs label fragments to improve its stability, however, how can I adjust the arguments to make it. I am looking forward to your prompt reply!! Thanks
like this【readTable <- MULTIseq.preProcess(R1 = '/path/to/R1.fastq.gz', R2 = '/path/to/R2.fastq.gz', cellIDs = cell.id.vec, cell=c(1,16), umi=c(17,28), tag=c(1,8))】
