### ISSUE TITLE
License for this repo?

### ISSUE THREAD

**Issue by wflynny** [chris-mcginnis-ucsf/MULTI-seq#20]
Annoying question:  I've reimplemented this code in python which I would like to make public but first want to make sure that I credit your work and choose a compatible license.  This repo doesn't appear to an explicit license, and googling around shows maybe it's under [CC0](https://rdrr.io/github/chris-mcginnis-ucsf/MULTI-seq/).  

Is this code licensed?  If you're looking for guidance on choosing a license, [choosealicense.com](https://choosealicense.com/) is helpful.

Thanks!

**Comment by chris-mcginnis-ucsf** [comment]
Hi @wflynny ,

Apologies for the delayed response. I only check the issues page here sporadically.

Feel free to use the code in any way you see fit. Please just include a reference to our MULTI-seq paper to ensure that our work is properly cited.

Chris

**Comment by wflynny** [comment]
Great, thanks Chris!
