### ISSUE TITLE
Error when reading indrops3 data

### ISSUE THREAD

**Issue by naumenko-sa** [chris-mcginnis-ucsf/MULTI-seq#21]
Hello Chris!

Thanks for developing and supporting Multi-seq!

I'm trying to load and analyze indrops3 data: https://singlecellcore.hms.harvard.edu/resources
I emulated 10X reads by merging 4 indrops3 reads into two, and loading them with:

```
readTable <- MULTIseq.preProcess(R1 = "data/06_indrop3_to_10x/multiseq10x_1.fq.gz", 
                                 R2 = "data/06_indrop3_to_10x/multiseq10x_2.fq.gz", 
                                 cellIDs = cell_ids$cell_barcode, 
                                 cell = c(1, 16),
                                 umi = c(17, 22), 
                                 tag = c(1, 8))
```

It errors with:
```
#[1] "Reading in R1..."
#[1] "Reading in R2..."
#[1] "Assembling read table..."
#Error in .Call2("C_solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  : 
#  solving row 12080: 'allow.nonnarrowing' is FALSE and the supplied end (8) is > refwidth
```

Do you have any suggestions on how to proceed?

Sergey

**Comment by chris-mcginnis-ucsf** [comment]
Hi @naumenko-sa ,

Apologies for the delayed response. Did you end up figuring this out? Email me at chris.mcginnis@ucsf.edu if you want to chat more (I do not regularly check this help page). 

Chris

**Comment by romunov** [comment]
Please see #2. I solved it by adding cell, umi and tag

```
readTable <- MULTIseq.preProcess(
  R1 = "../data/barcodes/SRR11393504_1_paired_filtered.fastq.gz",
  R2 = "../data/barcodes/SRR11393504_2_paired_filtered.fastq.gz",
  cellIDs = mix3b_keep,
  cell = c(1, 16), # in R1
  umi = c(17, 26), # in R1
  tag = c(1, 8)
)
```

as the defaults do not match the chemistry. For reference, I'm working with [this repository](https://github.com/dpcook/emt_dynamics/blob/master/processing_notebooks/timecourse_processing.Rmd#L219).
