### ISSUE TITLE
Hide classifyCells Print-out

### ISSUE THREAD

**Issue by Albert-Shuai** [chris-mcginnis-ucsf/MULTI-seq#25]
Hi:

this is an amazing package but each time when I run classifyCells, it gives me tons of print out, like the example I give below. Is there anyway we can hide those printout? Thanks!

**Comment by Albert-Shuai** [comment]
[1] "No threshold found for Bar1..."
[1] "No threshold found for Bar2..."
[1] "No threshold found for Bar3..."
[1] "No threshold found for Bar5..."
[1] "No threshold found for Bar6..."
[1] "No threshold found for Bar7..."

**Comment by chris-mcginnis-ucsf** [comment]
Hi @Albert-Shuai -- Those messages are annoying by design because they are meant to inform the user that the classification algorithm is not working properly. Did you perform the barcode tSNE check to make sure that you are classifying only barcodes present in your data?

Chris

**Comment by Albert-Shuai** [comment]
Hi. Thanks for response.

I check the barcode sum and none of them sums to 0. I repeatedly remove negative cells as suggested in tutorial. It works well for the first iteration, but starting from 2nd iteration, there are some printing out like:

[1] "No threshold found for Bar9..."
[1] "No threshold found for Bar9..."
[1] "No threshold found for Bar9..."
[1] "No threshold found for Bar9..."

And after I repeat it till 4 times, the print out disappears.

I repeat in total 8 times to remove negative cells.

So may I learn which part I go wrong? thanks!

**Comment by chris-mcginnis-ucsf** [comment]
Hi @Albert-Shuai ,

You can still have a low-quality barcode that has counts in cells, for example due to ambient barcodes. So just checking whether the sum is > 0 does not suffice, you should interrogate the barcode space to see if there is a cluster enriched for Bar9.
