### ISSUE TITLE
cells being called HTO1_HTO1?

### ISSUE THREAD

**Issue by bharris12** [chris-mcginnis-ucsf/MULTI-seq#28]
When I run multiseq demux I sometimes get cells that have the label HTO1_HTO1 and are labeled as doublets. What part of the algorithm is doing that? 

Thank you,
Ben

**Comment by chris-mcginnis-ucsf** [comment]
Hi @bharris12 ,

I have no idea, but looks like you are using the Seurat version? If so, you should reach out to them, or provide code.

Chris
