### ISSUE TITLE
MULTISeqDemux function error: "No threshold found for CMO302

### ISSUE THREAD

**Issue by JS0715** [chris-mcginnis-ucsf/MULTI-seq#29]
Hi
I am working on analyzing multiplexing (cellplex and TotalSeqA) data. I used HTOdemux for demultiplexing samples and it worked fine for both cellplex and totalseqA data however when I used MULTISeqDemux function for demultiplexing cellplex data it is giving me error saying "No threshold found for CMO302"

MULTISeqDemux function worked on TotalSeqA data though. Can you please help me understand what's going on?

<img width="575" alt="MultiSeqdemux-error" src="https://user-images.githubusercontent.com/62351024/198011023-2adedfd3-98e3-4495-a56e-cad192e68a1a.png">

Thanks!

**Comment by chris-mcginnis-ucsf** [comment]
Hi @JS0715 ,

That error is thrown when there is a low-quality barcode present. Have you checked barcode space to ensure that CM302 marks a specific cluster? 

Chris
