### ISSUE TITLE
 findReclassCells

### ISSUE THREAD

**Issue by lk9-lnx** [chris-mcginnis-ucsf/MULTI-seq#3]
I am trying to use  findReclassCells function, but getting the following error, even though the row names are unique. 

> reclass.cells <- findReclassCells(bar.table, names(final.calls)[which(final.calls=="Negative")])
[1] "Normalizing barode data..."
[1] "Pre-allocating data structures..."
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique values when setting 'row.names': ‘AAACCTGCAGCTCCGA-1’, ‘AAACGGGAGTGTACGG-1’, ‘AAACGGGCAATCAGAA-1’, ‘AAACGGGTCGACAGCC-1’, ‘AAAGCAACAAAGCAAT-1’, ‘AAATGCCGTTCAGTAC-1’, ‘AACACGTGTACTCTCC-1’, ‘AACACGTTCCGCATCT-1’, ‘AACCATGTCAGTGCAT-1’, ‘AACCATGTCCGTAGGC-1’

**Comment by chris-mcginnis-ucsf** [comment]
Hmmm, don't know what to say without a more information. Without meaning to sound too patronizing, my guess would be that your cellIDs included duplicates...

**Comment by RM-SCB** [comment]
I got the same error and indeed some duplicates were introduced in the negative fraction. I didn't check at which step exactly but you can just filter them before running findReclassCells: 
`final.calls <- final.calls[!duplicated(names(final.calls))]`

**Comment by alexfernandes8a** [comment]
I was getting the same error as @sri540. Using the solution provided by @r-mvl, I was able to continue the analysis but now I am getting the following error:

> [1] "Determining classifications for negative cells across all BCs, all q..."
> Error in if (L == 0) warning("Binning grid too coarse for current (small) bandwidth: consider increasing 'gridsize'") : 
>   missing value where TRUE/FALSE needed

Any idea of how to actually solve this?

**Comment by chris-mcginnis-ucsf** [comment]
hmmm... sort of hard to advise without the actual code. Could you forward along your code, as well as screenshots of what the data looks like (i.e., screenshot of head(cellIDs), head(bar.ref), head(bar.table), head(read.table), etc.)
