### ISSUE TITLE
MULTIseq.preprocess function

### ISSUE THREAD

**Issue by Alina-Ba** [chris-mcginnis-ucsf/MULTI-seq#30]
Hi! 
I'm having a memory problem for the MULTIseq.preprocess function. My fastq files are around 4-5GB. When I run the function I run out of memory as it consumes more than 100GB. Is this normal?

Thanks a lot for your help with this!!

Best wishes,
Alina

**Comment by chris-mcginnis-ucsf** [comment]
Hi @Alina-Ba ,

Yeah this function doesn't work super well with huge fastqs... I would either (i) downsample the FASTQs beforehand or (ii) use a different fastq processing tool (e.g., kb kite).

Chris
