### ISSUE TITLE
Download of test data fails

### ISSUE THREAD

**Issue by aghr** [chris-mcginnis-ucsf/MULTI-seq#31]
Following this link:

Download example dataset for trying deMULTIplex here: https://ucsf.box.com/s/ibo5t6y0a0a3dde68o5xnedjmajsujxk

I see this error:
This shared file or folder link has been removed or is unavailable to you.

**Comment by chris-mcginnis-ucsf** [comment]
@aghr -- fixed, just added .Robj file to the repo instead (should've done that from the beginning...)

Chris
