### ISSUE TITLE
Feature Request: preProcess barcodes as variable instead of hard coded

### ISSUE THREAD

**Issue by omansn** [chris-mcginnis-ucsf/MULTI-seq#4]
Hi Chris,

I'd like to use deMULTIplex for 12bp barcodes. Currently, the barcode length is hard coded in MULTIseq.preProcess for the 8bp multi-seq barcodes:
```
if (chemistry == "V2") {
     readTable <- cbind(as.data.frame(subseq(sread(r1),1,16)),
                       as.data.frame(subseq(sread(r1),17,26)),
                       as.data.frame(subseq(sread(r2),1,8))) #HERE
    colnames(readTable) <- c("Cell","UMI","Sample")
    gc()
    ind <- which(readTable$Cell %in% cellIDs)
    readTable <- readTable[ind, ]
    return(readTable)
  }
```

To make demultiplex compatible with other multiplexing methods as well as custom barcodes, It would be great if barcode length were coded as a variable so users can put in their own without modifying the source code.

Thanks!
Nathan

**Comment by chris-mcginnis-ucsf** [comment]
Hey Nathan,

Good call. I was actually just getting frustrated at my own code for this same reason. Will update soon.

Chris

**Comment by chris-mcginnis-ucsf** [comment]
Added -- thanks for the suggestions!
